"""Fixed metadata for the incident login-chain task pack."""

from __future__ import annotations

from cyber_agent.contracts.task_pack import TaskPackManifest

INCIDENT_LOGIN_CHAIN_TASK_PACK_ID = "incident.login_chain"
INCIDENT_LOGIN_CHAIN_TASK_PACK_VERSION = "1.0.0"
INCIDENT_LOGIN_CHAIN_TASK_TYPE = "incident.login_chain"
INCIDENT_LOGIN_CHAIN_INVENTORY_TOOL_ID = "incident.log_inventory"
INCIDENT_LOGIN_CHAIN_SEARCH_TOOL_ID = "incident.log_search"
INCIDENT_LOGIN_CHAIN_REQUIRED_TOOLS = (
    INCIDENT_LOGIN_CHAIN_INVENTORY_TOOL_ID,
    INCIDENT_LOGIN_CHAIN_SEARCH_TOOL_ID,
)
INCIDENT_LOGIN_CHAIN_INVENTORY_CAPABILITY = "incident.log_inventory"
INCIDENT_LOGIN_CHAIN_SEARCH_CAPABILITY = "incident.log_search"
INCIDENT_LOGIN_CHAIN_CAPABILITIES = (
    INCIDENT_LOGIN_CHAIN_INVENTORY_CAPABILITY,
    INCIDENT_LOGIN_CHAIN_SEARCH_CAPABILITY,
)
INCIDENT_LOGIN_CHAIN_VERIFIER_ID = "incident.login_chain"
INCIDENT_LOGIN_CHAIN_REPORT_TEMPLATE = "incident.login_chain"
INCIDENT_LOGIN_CHAIN_SECURITY_POLICY = "scope-policy/1.0"

_MANIFEST = TaskPackManifest(
    task_pack_id=INCIDENT_LOGIN_CHAIN_TASK_PACK_ID,
    version=INCIDENT_LOGIN_CHAIN_TASK_PACK_VERSION,
    task_type=INCIDENT_LOGIN_CHAIN_TASK_TYPE,
    required_tools=INCIDENT_LOGIN_CHAIN_REQUIRED_TOOLS,
    verifier=INCIDENT_LOGIN_CHAIN_VERIFIER_ID,
    report_template=INCIDENT_LOGIN_CHAIN_REPORT_TEMPLATE,
    security_policy=INCIDENT_LOGIN_CHAIN_SECURITY_POLICY,
)


def incident_login_chain_manifest() -> TaskPackManifest:
    """Return an isolated copy of the fixed least-privilege manifest."""

    return _MANIFEST.model_copy(deep=True)


__all__ = [
    "INCIDENT_LOGIN_CHAIN_CAPABILITIES",
    "INCIDENT_LOGIN_CHAIN_INVENTORY_CAPABILITY",
    "INCIDENT_LOGIN_CHAIN_INVENTORY_TOOL_ID",
    "INCIDENT_LOGIN_CHAIN_REPORT_TEMPLATE",
    "INCIDENT_LOGIN_CHAIN_REQUIRED_TOOLS",
    "INCIDENT_LOGIN_CHAIN_SEARCH_CAPABILITY",
    "INCIDENT_LOGIN_CHAIN_SEARCH_TOOL_ID",
    "INCIDENT_LOGIN_CHAIN_SECURITY_POLICY",
    "INCIDENT_LOGIN_CHAIN_TASK_PACK_ID",
    "INCIDENT_LOGIN_CHAIN_TASK_PACK_VERSION",
    "INCIDENT_LOGIN_CHAIN_TASK_TYPE",
    "INCIDENT_LOGIN_CHAIN_VERIFIER_ID",
    "incident_login_chain_manifest",
]
